# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import clock_pb2 as clock__pb2


class ClockSynchronizerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTime = channel.unary_unary(
                '/ClockSynchronizer/GetTime',
                request_serializer=clock__pb2.TimeRequest.SerializeToString,
                response_deserializer=clock__pb2.TimeResponse.FromString,
                )
        self.SyncTime = channel.unary_unary(
                '/ClockSynchronizer/SyncTime',
                request_serializer=clock__pb2.SyncRequest.SerializeToString,
                response_deserializer=clock__pb2.SyncResponse.FromString,
                )


class ClockSynchronizerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClockSynchronizerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTime,
                    request_deserializer=clock__pb2.TimeRequest.FromString,
                    response_serializer=clock__pb2.TimeResponse.SerializeToString,
            ),
            'SyncTime': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncTime,
                    request_deserializer=clock__pb2.SyncRequest.FromString,
                    response_serializer=clock__pb2.SyncResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ClockSynchronizer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClockSynchronizer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClockSynchronizer/GetTime',
            clock__pb2.TimeRequest.SerializeToString,
            clock__pb2.TimeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SyncTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClockSynchronizer/SyncTime',
            clock__pb2.SyncRequest.SerializeToString,
            clock__pb2.SyncResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
